import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Lightbulb, AlertTriangle, BookOpen, Users } from "lucide-react";

export default function InstructionsPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <header className="text-center space-y-2">
        <h1 className="font-headline text-4xl md:text-5xl font-bold text-primary">
          How Nyaya Sahayak Works
        </h1>
        <p className="text-lg text-foreground/80 font-body">
          Understanding your AI-powered legal information tool.
        </p>
      </header>

      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <BookOpen className="h-6 w-6 text-accent" />
            Purpose of Nyaya Sahayak
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 font-body text-foreground/90">
          <p>
            Nyaya Sahayak is designed to provide initial guidance and help you identify potentially relevant Indian laws based on your natural language questions. Our goal is to make legal information more accessible and understandable as a starting point for your research.
          </p>
          <p>
            Think of it as a knowledgeable assistant that can point you in the right direction, but not as a replacement for a qualified legal professional.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <Lightbulb className="h-6 w-6 text-accent" />
            Using the AI Suggestion Tool
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 font-body text-foreground/90">
          <ol className="list-decimal list-inside space-y-2">
            <li>
              <strong>Navigate to "Ask AI":</strong> Find the "Ask AI" link in the navigation bar.
            </li>
            <li>
              <strong>Enter Your Question:</strong> In the provided text area, type your legal question or describe your situation in plain English. The more specific and clear your query, the better the AI can assist.
            </li>
            <li>
              <strong>Submit Your Query:</strong> Click the "Suggest Relevant Laws" button.
            </li>
            <li>
              <strong>Review Suggestions:</strong> The AI will process your question and display a list of Indian laws or legal sections that might be relevant to your query.
            </li>
            <li>
              <strong>Further Research:</strong> Use these suggestions as a starting point for more in-depth research or when consulting with a legal professional.
            </li>
          </ol>
        </CardContent>
      </Card>
      
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <Users className="h-6 w-6 text-accent" />
            Who is this for?
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 font-body text-foreground/90">
          <p>
            Nyaya Sahayak can be helpful for:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>Individuals seeking to understand their basic rights and obligations.</li>
            <li>Students researching legal topics.</li>
            <li>Small business owners trying to navigate legal requirements.</li>
            <li>Anyone curious about specific aspects of Indian law.</li>
          </ul>
        </CardContent>
      </Card>

      <Card className="border-destructive bg-destructive/10 shadow-md">
        <CardHeader className="flex flex-row items-center gap-2 text-destructive">
          <AlertTriangle className="h-7 w-7" />
          <CardTitle className="font-headline text-2xl">Important Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 font-body text-destructive/90">
          <p>
            The information provided by Nyaya Sahayak is for general informational and educational purposes only. It is generated by an AI and is <strong>not legal advice</strong>.
          </p>
          <p>
            Laws are complex and their application can vary significantly based on specific facts and circumstances. This tool does not create an attorney-client relationship.
          </p>
          <p>
            <strong>Always consult with a qualified legal professional</strong> for advice tailored to your specific situation. Do not rely solely on information from this tool for making legal decisions.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
